ToDoApp/ViewModels/ActiveListViewModel.cs
namespace ToDoApp.ViewModels
{
    public class ActiveListViewModel
    {
        public IEnumerable<ToDoViewModel> ToDos { get; set; }
    }
}

ToDoApp/ViewModels/AddViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoApp.ViewModels
{
    public class AddViewModel
    {
        [Required]
        public string Title { get; set; }
    }
}

ToDoApp/ViewModels/CompletedListViewModel.cs
namespace ToDoApp.ViewModels
{
    public class CompletedListViewModel
    {
        public IEnumerable<ToDoViewModel> ToDos { get; set; }
    }
}

ToDoApp/ViewModels/DeleteViewModel.cs
namespace ToDoApp.ViewModels
{
    public class DeleteViewModel
    {
        public string Id { get; set; }
    }
}

ToDoApp/ViewModels/EditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoApp.ViewModels
{
    public class EditViewModel
    {
        [Required]
        public Guid Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string RedirectUrl { get; set; }
    }
}

ToDoApp/ViewModels/ToDoViewModel.cs
using ToDoApp.Entities.Enums;

namespace ToDoApp.ViewModels
{
    public class ToDoViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public DateOnly Created { get; set; }
    }
}

ToDoApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ToDoApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ToDoApp/Controllers/ToDoController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using ToDoApp.ViewModels;
using UseCases.Enums;
using UseCases.Exceptions;
using UseCases.Handlers.ToDo.Commands.CompleteToDo;
using UseCases.Handlers.ToDo.Commands.CreateToDo;
using UseCases.Handlers.ToDo.Commands.DeleteToDo;
using UseCases.Handlers.ToDo.Commands.UpdateToDo;
using UseCases.Handlers.ToDo.Queries.GetToDoById;
using UseCases.Handlers.ToDo.Queries.GetToDoCollectionByStatus;

namespace ToDoApp.Controllers
{
    public class ToDoController : Controller
    {
        private readonly IMediator _mediator;

        public ToDoController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddViewModel viewModel)
        {
            if (ModelState.IsValid == false)
                return View(viewModel);

            var command = new CreateToDoCommand()
            {
                Title = viewModel.Title,
            };

            await _mediator.Send(command);

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ActiveList()
        {
            var query = new GetToDoCollectionByStatusQuery()
            {
                Status = ToDoStatus.Active,
            };

            var dto = await _mediator.Send(query);

            var viewModel = new ActiveListViewModel()
            {
                ToDos = dto.ToDos.Select(t => new ToDoViewModel()
                {
                    Created = t.Created,
                    Id = t.Id,
                    Title = t.Title,
                })
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id, string redirectUrl)
        {
            var command = new DeleteToDoCommand()
            {
                ToDoId = Guid.Parse(id),
            };
            try
            {
                await _mediator.Send(command);
            }
            catch (ToDoNotFoundException)
            {
                return NotFound();
            }
            catch
            {
                throw;
            }

            return Redirect(redirectUrl);
        }

        [HttpPost]
        public async Task<IActionResult> Complete(string id)
        {
            var command = new CompleteToDoCommand()
            {
                ToDoId = Guid.Parse(id),
            };

            try
            {
                await _mediator.Send(command);
            }
            catch (ToDoNotFoundException)
            {
                return NotFound();
            }
            catch
            {
                throw;
            }

            return RedirectToAction(nameof(ActiveList));
        }

        [HttpGet]
        public async Task<IActionResult> CompletedList()
        {
            var query = new GetToDoCollectionByStatusQuery()
            {
                Status = ToDoStatus.Completed,
            };

            var dto = await _mediator.Send(query);

            var viewModel = new CompletedListViewModel()
            {
                ToDos = dto.ToDos.Select(t => new ToDoViewModel()
                {
                    Created = t.Created,
                    Id = t.Id,
                    Title = t.Title,
                })
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id, string redirectUrl)
        {
            var query = new GetToDoByIdQuery()
            {
                ToDoId = Guid.Parse(id),
            };

            try
            {
                var dto = await _mediator.Send(query);

                var viewModel = new EditViewModel()
                {
                    Id = dto.Id,
                    Title = dto.Title,
                    RedirectUrl = redirectUrl
                };

                return View(viewModel);
            }
            catch (ToDoNotFoundException)
            {
                return NotFound();
            }
            catch
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditViewModel viewModel)
        {
            if (ModelState.IsValid == false)
                return View(viewModel);

            var command = new UpdateToDoCommand()
            {
                ToDoId = viewModel.Id,
                Title = viewModel.Title,
            };

            try
            {
                await _mediator.Send(command);
            }
            catch (ToDoNotFoundException)
            {
                return NotFound();
            }
            catch
            {
                throw;
            }

            return Redirect(viewModel.RedirectUrl);
        }
    }
}

ToDoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Add">Add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="ActiveList">List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="CompletedList">Completed list</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ToDoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoApp/Views/ToDo/ActiveList.cshtml
@model ActiveListViewModel

<h3>Active:</h3>


<ul class="list-group">
    @foreach (var item in Model.ToDos)
    {
        <li class="list-group-item">
            <div class="d-flex justify-content-between">
                <div>
                    <span>@item.Title, @item.Created</span>
                </div>

                <div class="d-flex">

                    <form class="form-inline mr-2" asp-action="Delete" asp-controller="ToDo"
                          asp-route-id="@item.Id" asp-route-redirectUrl="@Context.Request.Path" method="post">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>

                    <form class="form-inline mr-2" asp-action="Complete" asp-controller="ToDo" asp-route-id="@item.Id" method="post">
                        <button type="submit" class="btn btn-primary">Complete</button>
                    </form>

                    <a class="btn btn-info" asp-action="Edit" asp-controller="ToDo" asp-route-id="@item.Id"
                        asp-route-redirectUrl="@Context.Request.Path">Edit</a>
                </div>
            </div>
        </li>
    }

</ul>

ToDoApp/Views/ToDo/Add.cshtml
@model AddViewModel

<form class="form-inline" method="post" asp-action="Add" asp-controller="ToDo">
    <input class="form-control" type="text" asp-for="Title" />
    <input class="btn btn-primary" type="submit" />
</form>

ToDoApp/Views/ToDo/CompletedList.cshtml
@model CompletedListViewModel

<h3>Completed:</h3>

<ul class="list-group">
    @foreach (var item in Model.ToDos)
    {
        <li class="list-group-item">
            <div class="d-flex justify-content-between">
                <div>
                    <span class="text-light bg-info rounded">@item.Title, @item.Created</span>
                </div>

                <div class="d-flex">
                    <form class="form-inline mr-2" asp-action="Delete" asp-controller="ToDo"
                          asp-route-id="@item.Id" asp-route-redirectUrl="@Context.Request.Path" method="post">
                
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>

        </li>
    }
</ul>

ToDoApp/Views/ToDo/Edit.cshtml
@model EditViewModel

<form asp-action="Edit" asp-controller="ToDo" method="post">
    <input hidden asp-for="RedirectUrl" />
    <input hidden asp-for="Id" value="@Model.Id" />
    <input type="text" asp-for="Title" />

    <input type="submit"/>
</form>